In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r'C:\Users\USER\Desktop\5th sem\project1_daibatise\data\processed\mohammed_ajlan_p1w1_features.csv',parse_dates=["last_checkup_date"])

# classification and split

In [3]:
df.shape

(950, 21)

In [4]:
df['outcome'].value_counts(normalize=True)

outcome
0    0.712632
1    0.287368
Name: proportion, dtype: float64

In [5]:
df.head()

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,...,smoker,last_checkup_date,outcome,age_band,bmi_category,glucose_band,insulin_glucose_ratio,pregnancy_rate,since_checkup,activity_smoker
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,...,NO,2023-04-20,0,senior,normal,prediabetic,1.000000,0.000000,618,Unkown/NO
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,...,YES,2024-05-03,1,middle_aged,obese,diabetic,0.274510,0.000000,239,Medium/YES
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,...,UNKOWN,2023-07-08,0,middle_aged,overweight,diabetic,1.119718,0.000000,539,Low/UNKOWN
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,...,YES,2024-04-14,1,senior,overweight,prediabetic,1.024793,0.102941,258,Unkown/YES
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,...,NO,2024-01-27,0,senior,normal,prediabetic,0.943925,0.000000,336,Low/NO

In [6]:
feautre_cols=['age','pregnancies','glucose','blood_pressure','skin_thickness','insulin',
              'bmi','diabetes_pedigree','bmi_category','glucose_band']
x=df[feautre_cols]
y=df['outcome']
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category,glucose_band
0,79,0,124.000000,71.0,30.0,124.0,23.4,0.588,normal,prediabetic
1,37,0,153.000000,85.0,24.0,42.0,33.9,0.192,obese,diabetic
2,39,0,142.000000,68.0,22.0,159.0,26.9,0.777,overweight,diabetic
3,68,7,121.000000,88.0,26.0,124.0,29.0,1.217,overweight,prediabetic
4,75,0,107.000000,84.0,31.0,101.0,21.2,0.278,normal,prediabetic
...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.855165,81.0,34.0,124.0,40.3,0.641,obese,prediabetic
946,71,0,140.000000,64.0,37.0,124.0,33.4,0.116,obese,diabetic
947,40,0,130.000000,73.0,26.0,258.0,20.1,0.709,normal,diabetic
948,52,4,123.000000,76.0,22.0,189.0,38.9,0.540,obese,prediabetic
949,42,0,114.000000,73.0,34.0,124.0,28.2,0.819,overweight,prediabetic

encode your banded feauters

In [7]:
x=pd.get_dummies(x,drop_first=True)

In [8]:
x.shape

(950, 13)

In [9]:
x

,age,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,bmi_category_obese,bmi_category_overweight,bmi_category_underweight,glucose_band_normal,glucose_band_prediabetic
0,79,0,124.000000,71.0,30.0,124.0,23.4,0.588,False,False,False,False,True
1,37,0,153.000000,85.0,24.0,42.0,33.9,0.192,True,False,False,False,False
2,39,0,142.000000,68.0,22.0,159.0,26.9,0.777,False,True,False,False,False
3,68,7,121.000000,88.0,26.0,124.0,29.0,1.217,False,True,False,False,True
4,75,0,107.000000,84.0,31.0,101.0,21.2,0.278,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,64,2,117.855165,81.0,34.0,124.0,40.3,0.641,True,False,False,False,True
946,71,0,140.000000,64.0,37.0,124.0,33.4,0.116,True,False,False,False,False
947,40,0,130.000000,73.0,26.0,258.0,20.1,0.709,False,False,False,False,False
948,52,4,123.000000,76.0,22.0,189.0,38.9,0.540,True,False,False,False,True
949,42,0,114.000000,73.0,34.0,124.0,28.2,0.819,False,True,False,False,True

In [10]:
x.columns

Index(['age', 'pregnancies', 'glucose', 'blood_pressure', 'skin_thickness',
       'insulin', 'bmi', 'diabetes_pedigree', 'bmi_category_obese',
       'bmi_category_overweight', 'bmi_category_underweight',
       'glucose_band_normal', 'glucose_band_prediabetic'],
      dtype='str')

split into tr

In [11]:
import sys
print(sys.executable)

c:\Users\USER\Desktop\5th sem\project1_daibatise\my_env\Scripts\python.exe

In [12]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size=0.2, random_state=42, stratify=y
)

In [13]:
x_test.shape

(190, 13)

In [14]:
x_train.shape

(760, 13)

In [15]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

outcome
0    0.713158
1    0.286842
Name: proportion, dtype: float64
outcome
0    0.710526
1    0.289474
Name: proportion, dtype: float64